# run: conda env create --file environment.yml
name: easie
dependencies:
- joblib==1.3.0
- matplotlib==3.7.2
- networkx==3.1
- numpy==1.25.1
- pandas==2.0.3
- pip==23.2.1
- rdkit==2023.03.2
- tqdm==4.65.00
- pip:
  - rdchiral==1.1.0
  - rxnmapper==0.3.0
